### PR TITLE
Reorganize file structure

### PR DESCRIPTION
**Pull request by Seth-Harlaar**
Main differences:
- Removed cooklang-py submodule
- Put flex/bison automatically generated files in parserFiles/
- Moved python submodule files to cooklang-py repo, including module testing files

### CODE REVIEW

**Comment by Seth-Harlaar** [comment]
Failed because testing was moved to the cooklan-py repository, decision is open for discussion.

**Comment by Seth-Harlaar** [comment]
Also an explanation for the parserFiles/ folder: @Net-Mist suggested that the automatically generated files from flex and bison be put in a separate location so that it is more clear that those files are automatically generated.

**Comment by dubadub** [comment]
Cool, should we also move `Cooklang.l` and `Cooklang.y` to `/src`?

**Review by Net-Mist — APPROVED** [review]

**Comment by Net-Mist** [comment]
@dubadub That's a good idea.

**Review by dubadub — APPROVED** [review]

**Review by Net-Mist — APPROVED** [review]

**Pull request merged**
